In [1]:
import dataloader as dl

In [2]:
# Test the dataloader
dl.markets.crypto.get_symbols()

            date     iexId  isEnabled                  name    symbol    type
8709  2019-01-23  10000000       True           Bitcoin USD   BTCUSDT  crypto
8710  2019-01-23  10000001       True               EOS USD   EOSUSDT  crypto
8711  2019-01-23  10000002       True          Ethereum USD   ETHUSDT  crypto
8712  2019-01-23  10000003       True      Binance Coin USD   BNBUSDT  crypto
8713  2019-01-23  10000004       True          Ontology USD   ONTUSDT  crypto
8714  2019-01-23  10000005       True      Bitcoin Cash USD   BCCUSDT  crypto
8715  2019-01-23  10000006       True           Cardano USD   ADAUSDT  crypto
8716  2019-01-23  10000007       True            Ripple USD   XRPUSDT  crypto
8717  2019-01-23  10000008       True               TrueUSD  TUSDUSDT  crypto
8718  2019-01-23  10000009       True              TRON USD   TRXUSDT  crypto
8719  2019-01-23  10000010       True          Litecoin USD   LTCUSDT  crypto
8720  2019-01-23  10000011       True  Ethereum Classic USD   ETCUSDT  crypto
8721  2019-01-23  10000012       True             MIOTA USD  IOTAUSDT  crypto
8722  2019-01-23  10000013       True              ICON USD   ICXUSDT  crypto
8723  2019-01-23  10000014       True               NEO USD   NEOUSDT  crypto
8724  2019-01-23  10000015       True           VeChain USD   VENUSDT  crypto
8725  2019-01-23  10000016       True    Stellar Lumens USD   XLMUSDT  crypto
8726  2019-01-23  10000017       True              Qtum USD  QTUMUSDT  crypto

In [4]:
dl.markets.

          date  isHalfday  litVolume  marketShare  routedVolume     volume
0   2019-01-22      False   54008830      0.02495      28047683  202904421
1   2019-01-18      False   56941782      0.02573      32731871  209720796
2   2019-01-17      False   50612305      0.02735      31694991  200303462
3   2019-01-16      False   56139518      0.02761      36326805  209197744
4   2019-01-15      False   50079138      0.02698      33089471  191510571
5   2019-01-14      False   48945972      0.02810      29161151  194668593
6   2019-01-11      False   49391833      0.02818      31206184  193179889
7   2019-01-10      False   52621002      0.02687      31923325  202631579
8   2019-01-09      False   65716673      0.02847      36175745  235272634
9   2019-01-08      False   63780652      0.02724      34511560  223062999
10  2019-01-07      False   69689751      0.02727      27382095  225358642
11  2019-01-04      False   72406498      0.02621      30679607  231587567
12  2019-01-03      False   69490684      0.02664      30291387  219799263
13  2019-01-02      False   68094279      0.02543      22701507  200842287